 "use client";
import {useState} from "react";
import {supabaseBrowser} from "../lib/supabase";
const products=[
{id:"coffee-1",c:"Cà phê",n:"Cà phê sữa",p:39000,i:"https://images.unsplash.com/photo-1461023058943-07cb3f5b9c4a?auto=format&fit=crop&w=700&q=80",d:"Đậm vị cà phê, dịu ngọt sữa."},
{id:"coffee-2",c:"Cà phê",n:"Americano",p:39000,i:"https://images.unsplash.com/photo-1497515114629-f71d768fd07c?auto=format&fit=crop&w=700&q=80",d:"Thanh, sạch và thơm."},
{id:"milk-1",c:"Trà sữa",n:"Trà sữa truyền thống",p:49000,i:"https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=700&q=80",d:"Béo nhẹ, thơm trà, trân châu."},
{id:"milk-2",c:"Trà sữa",n:"Matcha latte",p:55000,i:"https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=700&q=80",d:"Matcha xanh, sữa mịn."},
{id:"tea-1",c:"Trà",n:"Trà đào cam sả",p:49000,i:"https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=700&q=80",d:"Tươi mát, thơm đào và sả."},
{id:"tea-2",c:"Trà",n:"Trà vải hoa hồng",p:52000,i:"https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=700&q=80",d:"Hương hoa nhẹ, vị vải thanh."},
{id:"food-1",c:"Bánh & Đồ ăn",n:"Croissant bơ",p:42000,i:"https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=700&q=80",d:"Giòn ngoài, mềm thơm bên trong."},
{id:"food-2",c:"Bánh & Đồ ăn",n:"Bánh tiramisu",p:59000,i:"https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=700&q=80",d:"Mềm mịn, cà phê và cacao."}];
const money=(n:number)=>n.toLocaleString("vi-VN")+"đ";
export default function Home(){const q=new URLSearchParams(typeof window==="undefined"?"":location.search);const table=q.get("table")||"07";const [cat,setCat]=useState("Tất cả");const [chosen,setChosen]=useState<any>(null);const [cart,setCart]=useState<any[]>([]);const [staff,setStaff]=useState(false);const [note,setNote]=useState("");const [sugar,setSugar]=useState("50%");const [ice,setIce]=useState("50%");const [size,setSize]=useState("M");const [tops,setTops]=useState<string[]>([]);const [showCart,setShowCart]=useState(false);const [sent,setSent]=useState(false);
const shown=cat==="Tất cả"?products:products.filter(x=>x.c===cat);
async function callStaff(){try{await fetch("/api/staff-call",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({table})})}finally{setStaff(false);setSent(true)}}
function add(){if(!chosen)return;let extra=size==="L"?10000:0;const tp=tops.reduce((a,t)=>a+(t==="Trân châu đen"?5000:t==="Pudding"?7000:10000),0);setCart([...cart,{...chosen,p:chosen.p+extra+tp,size,sugar,ice,tops,note}]);setChosen(null);setNote("");setTops([])}
async function order(){if(!cart.length)return;await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({table,payment_method:"cash",items:cart})});setCart([]);setShowCart(false);setSent(true)}
return <div className="wrap"><section className="hero"><div className="logo">OMELY COFFEE</div><div className="pill">BÀN {table}</div><div><h1>Chậm một chút.<br/>Thưởng thức nhiều hơn.</h1><p>Coffee • Tea • Bakery • Slow moments</p></div></section><main className="content"><h2 style={{fontWeight:500}}>Thực đơn hôm nay</h2><div className="cats">{["Tất cả","Cà phê","Trà sữa","Trà","Bánh & Đồ ăn"].map(x=><button key={x} className={"cat "+(cat===x?"active":"")} onClick={()=>setCat(x)}>{x}</button>)}</div><div className="grid">{shown.map(x=><article className="card" key={x.id}><div className="photo" style={{backgroundImage:`url(${x.i})`}}/><div className="info"><div className="tag">{x.c}</div><div className="name">{x.n}</div><div className="desc">{x.d}</div><div className="row"><b>{money(x.p)}</b><button className="add" onClick={()=>setChosen(x)}>+</button></div></div></article>)}</div></main><div className="bar"><button className="staff" onClick={()=>setStaff(true)}>🔔 GỌI NHÂN VIÊN</button><button className="cart" onClick={()=>setShowCart(true)}>🛍 GIỎ HÀNG <b>{money(cart.reduce((a,x)=>a+x.p,0))}</b></button></div>
{chosen&&<div className="modal"><div className="sheet"><button className="close" onClick={()=>setChosen(null)}>×</button><h2>{chosen.n}</h2><p className="meta">{chosen.d}</p>{chosen.c!=="Bánh & Đồ ăn"&&<><div className="option"><b>Size</b><div className="choices">{["M","L"].map(x=><button className={"choice "+(size===x?"selected":"")} onClick={()=>setSize(x)}>{x}{x==="L"?" +10.000đ":""}</button>)}</div></div><div className="option"><b>Đường</b><div className="choices">{["0%","30%","50%","70%","100%"].map(x=><button className={"choice "+(sugar===x?"selected":"")} onClick={()=>setSugar(x)}>{x}</button>)}</div></div><div className="option"><b>Đá</b><div className="choices">{["Không đá","30%","50%","70%","100%"].map(x=><button className={"choice "+(ice===x?"selected":"")} onClick={()=>setIce(x)}>{x}</button>)}</div></div><div className="option"><b>Topping</b>{["Trân châu đen","Pudding","Kem cheese"].map(x=><label style={{display:"block",padding:"8px 0",fontFamily:"Arial"}}><input type="checkbox" checked={tops.includes(x)} onChange={e=>setTops(e.target.checked?[...tops,x]:tops.filter(t=>t!==x))}/> {x}</label>)}</div></>}<div className="option"><b>Ghi chú</b><textarea style={{width:"100%",padding:10,border:"1px solid #e8ded0",borderRadius:12}} value={note} onChange={e=>setNote(e.target.value)} placeholder="Ít ngọt, không ống hút..."/></div><button className="primary" onClick={add}>THÊM VÀO GIỎ</button></div></div>}
{showCart&&<div className="modal"><div className="sheet"><button className="close" onClick={()=>setShowCart(false)}>×</button><h2>Giỏ hàng • Bàn {table}</h2>{cart.map((x,i)=><div className="cartrow"><span><b>{x.n}</b><div className="meta">{x.size} • {x.sugar} đường • {x.ice} đá<br/>{x.tops.join(", ")||"Không topping"}</div></span><b>{money(x.p)}</b></div>)}<div className="total"><span>Tổng</span><span>{money(cart.reduce((a,x)=>a+x.p,0))}</span></div><button className="primary" onClick={order}>ĐẶT MÓN • TIỀN MẶT</button></div></div>}
{staff&&<div className="modal"><div className="sheet"><button className="close" onClick={()=>setStaff(false)}>×</button><div style={{textAlign:"center",padding:25}}><div style={{fontSize:55}}>🔔</div><h2>Gọi nhân viên?</h2><p>Yêu cầu sẽ gửi đến quầy cho Bàn {table}.</p><button className="primary" onClick={callStaff}>GỌI NHÂN VIÊN</button></div></div></div>}
{sent&&<div className="modal"><div className="sheet" style={{textAlign:"center"}}><div style={{fontSize:55}}>☕</div><h2>Đã gửi</h2><p>Nhân viên/quầy đã nhận thông báo.</p><button className="primary" onClick={()=>setSent(false)}>TIẾP TỤC</button></div></div>}</div>}
